// Generated by gencpp from file ros_proj/customMsg.msg
// DO NOT EDIT!


#ifndef ROS_PROJ_MESSAGE_CUSTOMMSG_H
#define ROS_PROJ_MESSAGE_CUSTOMMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_proj
{
template <class ContainerAllocator>
struct customMsg_
{
  typedef customMsg_<ContainerAllocator> Type;

  customMsg_()
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , topic()  {
    }
  customMsg_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , topic(_alloc)  {
  (void)_alloc;
    }



   typedef float _latitude_type;
  _latitude_type latitude;

   typedef float _longitude_type;
  _longitude_type longitude;

   typedef float _altitude_type;
  _altitude_type altitude;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topic_type;
  _topic_type topic;





  typedef boost::shared_ptr< ::ros_proj::customMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_proj::customMsg_<ContainerAllocator> const> ConstPtr;

}; // struct customMsg_

typedef ::ros_proj::customMsg_<std::allocator<void> > customMsg;

typedef boost::shared_ptr< ::ros_proj::customMsg > customMsgPtr;
typedef boost::shared_ptr< ::ros_proj::customMsg const> customMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_proj::customMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_proj::customMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_proj::customMsg_<ContainerAllocator1> & lhs, const ::ros_proj::customMsg_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.topic == rhs.topic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_proj::customMsg_<ContainerAllocator1> & lhs, const ::ros_proj::customMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_proj

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_proj::customMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_proj::customMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_proj::customMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_proj::customMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_proj::customMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_proj::customMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_proj::customMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d622bc11a41e3b0036750a62b226b234";
  }

  static const char* value(const ::ros_proj::customMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd622bc11a41e3b00ULL;
  static const uint64_t static_value2 = 0x36750a62b226b234ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_proj::customMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_proj/customMsg";
  }

  static const char* value(const ::ros_proj::customMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_proj::customMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 latitude\n"
"float32 longitude\n"
"float32 altitude\n"
"string topic\n"
;
  }

  static const char* value(const ::ros_proj::customMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_proj::customMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.topic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct customMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_proj::customMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_proj::customMsg_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
    s << indent << "topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.topic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_PROJ_MESSAGE_CUSTOMMSG_H
