// Generated by gencpp from file ros_proj/custom_msg.msg
// DO NOT EDIT!


#ifndef ROS_PROJ_MESSAGE_CUSTOM_MSG_H
#define ROS_PROJ_MESSAGE_CUSTOM_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_proj
{
template <class ContainerAllocator>
struct custom_msg_
{
  typedef custom_msg_<ContainerAllocator> Type;

  custom_msg_()
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , vehicleType()  {
    }
  custom_msg_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , vehicleType(_alloc)  {
  (void)_alloc;
    }



   typedef float _latitude_type;
  _latitude_type latitude;

   typedef float _longitude_type;
  _longitude_type longitude;

   typedef float _altitude_type;
  _altitude_type altitude;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _vehicleType_type;
  _vehicleType_type vehicleType;





  typedef boost::shared_ptr< ::ros_proj::custom_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_proj::custom_msg_<ContainerAllocator> const> ConstPtr;

}; // struct custom_msg_

typedef ::ros_proj::custom_msg_<std::allocator<void> > custom_msg;

typedef boost::shared_ptr< ::ros_proj::custom_msg > custom_msgPtr;
typedef boost::shared_ptr< ::ros_proj::custom_msg const> custom_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_proj::custom_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_proj::custom_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_proj::custom_msg_<ContainerAllocator1> & lhs, const ::ros_proj::custom_msg_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.vehicleType == rhs.vehicleType;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_proj::custom_msg_<ContainerAllocator1> & lhs, const ::ros_proj::custom_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_proj

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_proj::custom_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_proj::custom_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_proj::custom_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_proj::custom_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_proj::custom_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_proj::custom_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_proj::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7b02c3dfba0b2b08c53eb019d9e8b34";
  }

  static const char* value(const ::ros_proj::custom_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7b02c3dfba0b2b0ULL;
  static const uint64_t static_value2 = 0x8c53eb019d9e8b34ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_proj::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_proj/custom_msg";
  }

  static const char* value(const ::ros_proj::custom_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_proj::custom_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 latitude\n"
"float32 longitude\n"
"float32 altitude\n"
"string vehicleType\n"
;
  }

  static const char* value(const ::ros_proj::custom_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_proj::custom_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.vehicleType);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_proj::custom_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_proj::custom_msg_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
    s << indent << "vehicleType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.vehicleType);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_PROJ_MESSAGE_CUSTOM_MSG_H
